version: '3.1'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    env_file: ".env"
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000

  mongo:
    image: mongo
    env_file: ".env"

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    env_file: ".env"